import { NextSeo } from 'next-seo';
import { NEXT_SEO_DEFAULT } from '../next-seo-config';


export default function Head() {
  // return (
  //   <>
  //     <title>Create Next App</title>
  //     <meta content="width=device-width, initial-scale=1" name="viewport" />
  //     <meta name="description" content="Generated by create next app" />
  //     <link rel="icon" href="/favicon.ico" />
  //   </>
  // )
  return <NextSeo {...NEXT_SEO_DEFAULT} useAppDir={true} />;
}
